package com.example.ai

import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

data class DiffLine(
    val originalLine: String?,
    val proposedLine: String?,
    val type: Type
) {
    enum class Type { UNCHANGED, ADDED, DELETED, MODIFIED }
}

data class AiDiffResult(
    val explanation: String,
    val originalCode: String,
    val proposedCode: String,
    val diffLines: List<DiffLine>
)

class OpenCodeAiAssistant {

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    suspend fun generateCodeFixOrFeature(
        userPrompt: String,
        selectedCode: String,
        fullFileCode: String,
        filePath: String,
        apiKeyOverride: String = ""
    ): AiDiffResult = withContext(Dispatchers.IO) {
        val apiKey = apiKeyOverride.ifEmpty {
            try {
                BuildConfig::class.java.getField("GEMINI_API_KEY").get(null) as? String ?: ""
            } catch (e: Exception) {
                ""
            }
        }

        if (apiKey.isBlank()) {
            return@withContext generateFallbackDiff(
                selectedCode,
                fullFileCode,
                "API key not set. Please set your GEMINI_API_KEY in Settings."
            )
        }

        val systemInstruction = """
            You are OpenCode AI Assistant inside Idea Mobile Android IDE.
            Analyze the requested code and prompt. Return a valid JSON response with keys:
            - "explanation": Short summary of changes made.
            - "proposedCode": The full updated code for the file or block.
        """.trimIndent()

        val promptText = """
            File Path: $filePath
            User Request: $userPrompt
            
            Selected Code Context:
            $selectedCode
            
            Full File Code:
            $fullFileCode
        """.trimIndent()

        return@withContext try {
            val jsonBody = JSONObject().apply {
                put("contents", JSONArray().apply {
                    put(JSONObject().apply {
                        put("parts", JSONArray().apply {
                            put(JSONObject().put("text", "$systemInstruction\n\n$promptText"))
                        })
                    })
                })
            }

            val request = Request.Builder()
                .url("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=$apiKey")
                .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
                .build()

            val response = client.newCall(request).execute()
            val responseBody = response.body?.string() ?: ""

            if (!response.isSuccessful) {
                return@withContext generateFallbackDiff(
                    selectedCode,
                    fullFileCode,
                    "Gemini API Error (${response.code}): $responseBody"
                )
            }

            val responseJson = JSONObject(responseBody)
            val candidates = responseJson.optJSONArray("candidates")
            val text = candidates?.optJSONObject(0)
                ?.optJSONObject("content")
                ?.optJSONArray("parts")
                ?.optJSONObject(0)
                ?.optString("text") ?: ""

            parseAiResponse(text, fullFileCode)
        } catch (e: Exception) {
            generateFallbackDiff(selectedCode, fullFileCode, "Error contacting AI Assistant: ${e.localizedMessage}")
        }
    }

    private fun parseAiResponse(responseStr: String, originalCode: String): AiDiffResult {
        var explanation = "Code generated by OpenCode AI"
        var proposedCode = originalCode

        if (responseStr.contains("{") && responseStr.contains("}")) {
            try {
                val jsonStart = responseStr.indexOf("{")
                val jsonEnd = responseStr.lastIndexOf("}") + 1
                val json = JSONObject(responseStr.substring(jsonStart, jsonEnd))
                explanation = json.optString("explanation", explanation)
                proposedCode = json.optString("proposedCode", originalCode)
            } catch (e: Exception) {
                proposedCode = cleanCodeFence(responseStr)
            }
        } else {
            proposedCode = cleanCodeFence(responseStr)
        }

        val diffs = computeLineDiffs(originalCode, proposedCode)
        return AiDiffResult(
            explanation = explanation,
            originalCode = originalCode,
            proposedCode = proposedCode,
            diffLines = diffs
        )
    }

    private fun cleanCodeFence(text: String): String {
        return text.replace(Regex("```[a-zA-Z]*"), "").replace("```", "").trim()
    }

    private fun generateFallbackDiff(selectedCode: String, fullCode: String, message: String): AiDiffResult {
        val proposed = if (selectedCode.isNotBlank()) {
            fullCode.replace(selectedCode, "$selectedCode\n    // TODO: AI Generated enhancement")
        } else {
            "// $message\n$fullCode"
        }
        val diffs = computeLineDiffs(fullCode, proposed)
        return AiDiffResult(
            explanation = message,
            originalCode = fullCode,
            proposedCode = proposed,
            diffLines = diffs
        )
    }

    fun computeLineDiffs(orig: String, prop: String): List<DiffLine> {
        val origLines = orig.lines()
        val propLines = prop.lines()
        val result = mutableListOf<DiffLine>()

        val maxLines = maxOf(origLines.size, propLines.size)
        for (i in 0 until maxLines) {
            val o = origLines.getOrNull(i)
            val p = propLines.getOrNull(i)

            when {
                o == p -> result.add(DiffLine(o, p, DiffLine.Type.UNCHANGED))
                o != null && p != null -> result.add(DiffLine(o, p, DiffLine.Type.MODIFIED))
                o == null -> result.add(DiffLine(null, p, DiffLine.Type.ADDED))
                p == null -> result.add(DiffLine(o, null, DiffLine.Type.DELETED))
            }
        }
        return result
    }
}
